import Navbar from "@/components/navbar";
import "./globals.css";
import Providers from "./GlobalRedux/provider";
import AuthProvider from "@/components/authprovider";
import ToastContainers from "@/components/toastcontainers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <body className="bg-[#F6F6F6]">
          <AuthProvider>
            <Providers>
              <ToastContainers />
              <Navbar />
              {children}
            </Providers>
          </AuthProvider>
      </body>
    </html>
  );
}
